-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 23:33:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `altura` VARCHAR(4) NOT NULL,
  `peso` VARCHAR(6) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `cpf` CHAR(11) NULL UNIQUE,
  `Usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Usuario_email`),
  CONSTRAINT `fk_Personal_Usuario1`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `mydb`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treino` (
  `idTreino` int AUTO_INCREMENT NOT NULL ,
  `nome_exercicio` VARCHAR(45) NOT NULL,
  `repeticoes` VARCHAR(45) NOT NULL,
  `series` VARCHAR(45) NOT NULL,
  `Usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTreino`),
  FOREIGN KEY (`Usuario_email`) REFERENCES `mydb`.`Usuario` (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;